#! /bin/sh

sxhkd &

bspc monitor eDP-1 -d 一 二 三 四 五 六 七 八 九 十
bspc monitor HDMI-1 -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color  \#181818
bspc config focused_border_color \#000000
bspc config urgent_border_color  \#000000
bspc config presel_border_color  \#000000

feh --bg-scale ~/Pictures/Wallpaper/fireworks.jpg
compton -b
polybar --reload top &
polybar --reload top-external &
